name: Build and Deploy Azure Function

on:
  push:
    branches:
      - main
      - v-next

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      FUNCTION_PROJECT: src/FunctionsLight/Cloud5mins.ShortenerTools.FunctionsLight.csproj
      PUBLISH_PATH: AzUrlShortener1

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore ${{ env.FUNCTION_PROJECT }}

    - name: Publish Azure Function
      run: dotnet publish ${{ env.FUNCTION_PROJECT }} -c Release -o ${{ env.PUBLISH_PATH }}

    - name: Inspect publish output
      run: ls -la ${{ env.PUBLISH_PATH }}

    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: AzUrlShortener1
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        package: ${{ env.PUBLISH_PATH }}/
