# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core app to Azure Function App - AzUrlShortener1

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Setup DotNet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore and Publish Function App
        shell: pwsh
        run: |
          dotnet restore src/AzUrlShortener.sln
          dotnet publish src/FunctionsLight/FunctionsLight.csproj `
            -c Release `
            -o publish

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'AzUrlShortener1'
          slot-name: 'Production'
          package: publish
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C00C8A2B51154E169050B7D63AABD309 }}



